### ISSUE TITLE
Reconstruct only terrain with water

### ISSUE THREAD

**Issue by gsclara** [tudelft3d/City4CFD#3] opened 2023-07-14 12:25 UTC
Would it be possible to just reconstruct terrain and water? no buildings?

**Comment by ipadjen** [comment] 2023-07-14 15:06
By design the code tries to make sure that there are some buildings in the influence region, so I would say no.

You could maybe hack it by making a small polygon somewhere in the influence region with a height attribute.

**Comment by ipadjen** [comment] 2023-09-09 20:41
Closing this for now.

**Closed by ipadjen** 2023-09-09 20:41 UTC
